tap "jameslockman/tap", trusted: true
# Sophisticated file transfer program
brew "lftp"
# Swiss-army knife of markup format conversion
brew "pandoc"
brew "git"
brew "tmux"
brew "wget"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Driver for the Griffin PowerMate USB controller on modern Macs
cask "jameslockman/tap/griffin-powermate-agent"
# Menu bar customization tool
cask "swiftbar"
# TODO: add karabiner elements config file to dotfiles
cask "karabiner-elements"
cask "keyboard-maestro"
cask "launchbar"
cask "visual-studio-code"
cask "qlmarkdown"
vscode "alefragnani.project-manager"
vscode "britesnow.vscode-toggle-quotes"
vscode "clinyong.vscode-css-modules"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "humao.rest-client"
vscode "jmfirth.vsc-space-block-jumper"
vscode "jtr.vscode-position"
vscode "kamikillerto.vscode-colorize"
vscode "mechatroner.rainbow-csv"
# vscode "obrejla.netbeans-light-theme"
vscode "alesh-houdek.steno-light-theme"
vscode "oliverkovacs.word-count"
vscode "openai.chatgpt"
vscode "repreng.csv"
vscode "simonsiefke.svg-preview"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "tyriar.sort-lines"
vscode "wallabyjs.quokka-vscode"
vscode "yzane.markdown-pdf"
npm "corepack"
