tap "jameslockman/tap", trusted: true
# Sophisticated file transfer program
brew "lftp"
# Swiss-army knife of markup format conversion
brew "pandoc"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Driver for the Griffin PowerMate USB controller on modern Macs
cask "jameslockman/tap/griffin-powermate-agent"
# Menu bar customization tool
cask "swiftbar"
vscode "alefragnani.project-manager"
vscode "britesnow.vscode-toggle-quotes"
vscode "clinyong.vscode-css-modules"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "fleshywaffles.vs-code-clippy"
vscode "formulahendry.code-runner"
vscode "humao.rest-client"
vscode "jmfirth.vsc-space-block-jumper"
vscode "jtr.vscode-position"
vscode "kamikillerto.vscode-colorize"
vscode "mechatroner.rainbow-csv"
vscode "obrejla.netbeans-light-theme"
vscode "oliverkovacs.word-count"
vscode "openai.chatgpt"
vscode "repreng.csv"
vscode "rido3.wordcount"
vscode "ritwickdey.liveserver"
vscode "simonsiefke.svg-preview"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "tyriar.sort-lines"
vscode "unifiedjs.vscode-mdx"
vscode "wallabyjs.quokka-vscode"
vscode "yzane.markdown-pdf"
go "golang.org/x/tools/gopls"
npm "@vscode/vsce"
npm "aws-cdk"
npm "corepack"
npm "openclaw"
